#!/bin/bash
#script for automating cppProcessing2.0 launch

LD_LIBRARY_PATH="/dls_sw/prod/tools/RHEL6-x86_64/hdf5/1-8-15/prefix/lib" /
HDF5_DISABLE_VERSION_CHECK='1' 
(/usr/bin/time -v ./Profiling/cppProcessing2.0) &> profile_report.txt		#this must be run from top level directory of the project
echo $'\n' >> profile_report.txt
operf ./Profiling/cppProcessing2.0
opreport --symbols >> profile_report.txt
#gedit profile_report.txt &

python ./tools/profile_processing.py
