language: cpp
compiler: gcc
sudo: false
    
cache:
  directories:
  - $HOME/epics
  - $HOME/synapps
  
addons:
  apt:
    packages:
    - libhdf5-serial-dev
    - libboost-test-dev
    - libtbb-dev
  
before_install:
  - cat /usr/lib/pkgconfig/tbb.pc
  - pkg-config --libs-only-L tbb
  - pkg-config --libs-only-l tbb
  - pkg-config --libs tbb
  - pkg-config --cflags-only-I tbb
  - mkdir build && cd build
  - cmake ..

install:
  - pwd
  - make VERBOSE=1

before_script:
  - cd ..
  - pwd
script:
  - ./build/bin/pcvl-unittest --log_level=all
  - ./build/bin/pcvl-profiling 1 210 160 1 data/test_param_file.txt 

  
